server.port: 9090

logging:
  level:
    ROOT: DEBUG
    com.ecomshop.deskplus: DEBUG

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          auto: update
  mail:
    host: ${MAILGUN_HOST}
    port: ${MAILGUN_PORT}
    username: ${MAILGUN_USERNAME}
    password: ${MAILGUN_PASSWORD}
    properties:
      mail:
        transport.protocol: smtp
        smtp.starttls.enable: true
        smtp.starttls.required: true
        smtp.auth: true
        smtp.from: ${MAILGUN_FROM}
        default-encoding: UTF-8
        test-connection: false

mail.from.name: eCommerce Shop - Desk Plus

stripe:
  api-key: ${STRIPE_API_KEY}
  deskplus.default-plan: ${STRIPE_DEFAULT_PLAN}

deskplus:
  base-url: ${DESKPLUS_BASE}
  product-key: desk_plus
